### ISSUE TITLE
Compilation error on MacOS and Python 3.12 and 3.13 installed using pip

### ISSUE THREAD

**Issue by infusion** [snowflakedb/snowflake-ml-python#134]
Hello,

I just wanted to install the snowflake ML package and having trouble doing so using pip. When running pip install, I get the following error

<img width="1224" alt="image" src="https://github.com/user-attachments/assets/44c09dc4-eb2b-4a35-a85b-10a2a78d4a8b">

```
$ python3 --version
Python 3.13.0

$ pip3 --version
pip 24.3.1
```

Is there something I am missing? Thanks for your work!

**Comment by sfc-gh-jbahk** [comment]
Hi @infusion, thanks for raising this issue. Unfortunately, our support of versions is limited by the underlying Snowpark Python package (https://github.com/snowflakedb/snowpark-python), which ranges from Python 3.8-3.11. 3.12 will be supported in the future, but unclear as to the exact timeline as of now.

**Comment by kartikey-vyas** [comment]
bump -- when trying to install latest version on both python 3.12.5 and 3.11.14, get the following error on a fresh `uv` environment:

```
  × Failed to build `numba==0.53.1`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 50, in <module>
        File "<string>", line 47, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.11.14; only versions >=3.6,<3.10 are supported.
```

We have managed to install `snowflake-ml-python==1.8.3` in a python 3.12.5 environment, but the latest version causes issues.

**Comment by adanaviles** [comment]
> bump -- when trying to install latest version on both python 3.12.5 and 3.11.14, get the following error on a fresh `uv` environment:
> 
> ```
>   × Failed to build `numba==0.53.1`
>   ├─▶ The build backend returned an error
>   ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)
> 
>       [stderr]
>       Traceback (most recent call last):
>         File "<string>", line 14, in <module>
>         File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
>           self.run_setup()
>         File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 512, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/Users/kartikey/.cache/uv/builds-v0/.tmpaWjcLH/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
>           exec(code, locals())
>         File "<string>", line 50, in <module>
>         File "<string>", line 47, in _guard_py_ver
>       RuntimeError: Cannot install on Python version 3.11.14; only versions >=3.6,<3.10 are supported.
> ```
> 
> We have managed to install `snowflake-ml-python==1.8.3` in a python 3.12.5 environment, but the latest version causes issues.

We're facing the same error, however since we're working with Airflow we can not install the 1.8.3 version. Any support on this? Latest versions are not working in python 3.12 due to numba compatibility
